### PR TITLE
add a `MYSQLPORT` option

### PR DESCRIPTION
**Pull request by mtigas**
(I am a crazy person and do a crazy thing [tor onion service & port forwarding] to get into my database remotely 😬)

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
miiiiiiiiiiiiiike

**Comment by jeremybmerrill** [comment]
oh can you add a default?

**Comment by jeremybmerrill** [comment]
i'll merge it asap then

**Comment by mtigas** [comment]
`mysql.createConnection(...)` uses `3306` as a default ([per doc](https://www.npmjs.com/package/mysql#connection-options)), at least on my nodejs v6.2.0 + mysql@2.10.2.

```
$ MYSQLUSER=dump1090 MYSQLPASSWORD=dump1090 nodejs mapify.js A9B67C
query: select * from squitters where icao_addr = conv('A9B67C', 16,10) and lat is not null order by generated_datetime desc;
A9B67C.vg
/home/user/Code/dump1090-mapper/mapify.js:40
  if (err) throw err;

Error: connect ECONNREFUSED 127.0.0.1:3306
…
```

so I _think_ that's ok for existing behavior (null env var -> `3306`)

**Comment by jeremybmerrill** [comment]
I'll check tonight or tomorrow morning. Thanks!!

**Pull request merged**
